using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Dotnet.Libraries.Enums
{
    public enum EnumCmdType : int
    {
        HEART_BEAT_REQUEST = 10,
        HEART_BEAT_RESPONSE = 20,

        LOGIN_REQUEST = 100,
        LOGIN_REQUEST_FORCE = 101,
        LOGIN_RESPONSE = 110,

        LOGOUT_REQUEST = 200,
        LOGOUT_REQUEST_FORCE_LOGIN = 201,
        LOGOUT_REQUEST_TIMEOUT = 202,
        LOGOUT_RESPONSE = 210,

        SESSION_REFRESH_REQUEST = 300,
        SESSION_REFRESH_RESPONSE = 310,

        USER_ACCOUNT_ADD_REQUEST = 400,
        USER_ACCOUNT_ADD_RESPONSE = 401,
        USER_ACCOUNT_ID_CHECK_REQUEST = 402,
        USER_ACCOUNT_ID_CHECK_RESPONSE = 403,
        USER_ACCOUNT_EDIT_REQUEST = 410,
        USER_ACCOUNT_EDIT_RESPONSE = 411,
        USER_ACCOUNT_DELETE_REQUEST = 420,
        USER_ACCOUNT_DELETE_RESPONSE = 421, 

        USER_ACCOUNT_INFO_REQUEST = 430,
        USER_ACCOUNT_INFO_RESPONSE = 431,

        USER_ACCOUNT_ALL_REQUEST = 440,
        USER_ACCOUNT_ALL_RESPONSE = 441,

        USER_ACCOUNT_ALL_DELETE_REQUEST = 450,
        USER_ACCOUNT_ALL_DELETE_RESPONSE = 451,

        EVENT_DETECTION_REQUEST = 510,
        EVENT_DETECTION_RESPONSE = 511,
        SEARCH_EVENT_DETECTION_REQUEST = 512,
        SEARCH_EVENT_DETECTION_RESPONSE = 513,

        EVENT_MALFUNCTION_REQUEST = 520,
        EVENT_MALFUNCTION_RESPONSE = 521,
        SEARCH_EVENT_MALFUNCTION_REQUEST = 522,
        SEARCH_EVENT_MALFUNCTION_RESPONSE = 523,

        EVENT_ACTION_REQUEST = 530,
        EVENT_ACTION_RESPONSE = 531,
        SEARCH_EVENT_ACTION_REQUEST = 532,
        SEARCH_EVENT_ACTION_RESPONSE = 533,

        EVENT_CONNECTION_REQUEST = 540,
        EVENT_CONNECTION_RESPONSE = 541,
        SEARCH_EVENT_CONNECTION_REQUEST = 542,
        SEARCH_EVENT_CONNECTION_RESPONSE = 543,

        EVENT_CONTACT_ON_REQUEST = 550,
        EVENT_CONTACT_ON_RESPONSE = 551,

        EVENT_CONTACT_OFF_REQUEST = 560,
        EVENT_CONTACT_OFF_RESPONSE = 561,

        DEVICE_INFO_REQUEST = 610,
        DEVICE_INFO_RESPONSE = 611,

        DEVICE_DATA_REQUEST = 612,
        DEVICE_DATA_RESPONSE = 613,

        MAPPING_INFO_REQUEST = 614,
        MAPPING_INFO_RESPONSE = 615,
        
        CONTROLLER_DATA_REQUEST = 620,
        CONTROLLER_DATA_RESPONSE = 621,

        CONTROLLER_DATA_SAVE_REQUEST = 622,
        CONTROLLER_DATA_SAVE_RESPONSE = 623,

        SENSOR_DATA_REQUEST = 630,
        SENSOR_DATA_RESPONSE = 631,

        SENSOR_DATA_SAVE_REQUEST = 632,
        SENSOR_DATA_SAVE_RESPONSE = 633,

        CAMERA_DATA_REQUEST = 640,
        CAMERA_DATA_RESPONSE = 641,

        CAMERA_DATA_SAVE_REQUEST = 642,
        CAMERA_DATA_SAVE_RESPONSE = 643,

        /// <summary>
        /// Camera Option
        /// </summary>
        CAMERA_MAPPING_DATA_REQUEST = 650,
        CAMERA_MAPPING_DATA_RESPONSE = 651,

        CAMERA_MAPPING_SAVE_REQUEST = 652,
        CAMERA_MAPPING_SAVE_RESPONSE = 653,

        CAMERA_PRESET_DATA_REQUEST = 654,
        CAMERA_PRESET_DATA_RESPONSE = 655,

        CAMERA_PRESET_SAVE_REQUEST = 656,
        CAMERA_PRESET_SAVE_RESPONSE = 657,

        SETTING_INFO_REQUEST = 660,
        SETTING_INFO_RESPONSE = 661,

        SYMBOL_DATA_INFO_REQUEST = 710,
        SYMBOL_DATA_INFO_RESPONSE = 711,

        SYMBOL_DATA_LOAD_REQUEST = 720,
        SYMBOL_DATA_LOAD_RESPONSE = 721,

        SYMBOL_DATA_SAVE_REQUEST = 722,
        SYMBOL_DATA_SAVE_RESPONSE = 723,

        SYMBOL_DATA_REQUEST = 730,
        SYMBOL_DATA_RESPONSE = 731,

        SHAPE_SYMBOL_DATA_REQUEST = 740,
        SHAPE_SYMBOL_DATA_RESPONSE = 741,

        OBJECT_SHAPE_DATA_REQUEST = 750,
        OBJECT_SHAPE_DATA_RESPONSE = 751,

        MAP_FILE_LOAD_REQUEST = 810,
        MAP_FILE_LOAD_RESPONSE = 811,
        MAP_FILE_SAVE_REQUEST = 820,
        MAP_FILE_SAVE_RESPONSE = 821,

        MODE_WINDY_REQUEST = 910,
        MODE_WINDY_RESPONSE = 911,

        STATUS_UPDATE = 1000,

    }
}
